[package]
name = "migrator"
version = "0.1.0"
authors = ["Neeraj Jaiswal <neerajj85@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
glob = "*"
postgres = "0.17"
anyhow = "1.0"
