id = 1

[[change]]
dialect = "psql"
repeatable = true

[[change.up]]
# Only one of these three allowed
query = "create table some_table"
queries = ["create table some_table", "create table some_table2"]
sqlDataFile = { path = "./sql/file.sql" }
# Optional
[[change.down]]
query = """
droop table some_table
"""

[[change]]
dialect = "mysql"

[[change.up]]
query = """
SELECT * from some_table
"""
[[change.down]]
query = """
SELECT * from some_table
"""
